CREATE TABLE IF NOT EXISTS Locations
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR       NOT NULL,
    user_id   BIGINT REFERENCES users (id) NOT NULL ,
    latitude  DECIMAL(3, 6) NOT NULL,
    longitude DECIMAL(3, 6) NOT NULL

);