CREATE TABLE IF NOT EXISTS Locations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR       NOT NULL,
    user_id   BIGINT REFERENCES users (id),
    latitude  DECIMAL(3, 6) NOT NULL,
    longitude DECIMAL(3, 6) NOT NULL

);